version: '2.0'
services:
  app:
    image: ubuntu:20.04
    env:
      - SSH_PASS=
      - MONIKER=MyMoniker
      - VALIDATOR_KEY_JSON_BASE64=
      - GITHUB_REPOSITORY=https://github.com/Kava-Labs/kava
      - GO_VERSION=1.20.5
      - RPC=https://kava-rpc.polkachu.com:443
      - BINARY_VERSION=v0.25.0
      - BINARY=kava
      - DENOM=ukava
      - SNAPSHOT=https://snapshots.polkachu.com/snapshots/kava/kava_7659355.tar.lz4
      - PRUNING=everything
      - INDEXER=null
      - SNAPSHOT_INTERVAL=0
      - DISABLE_FASTNODE=true
      - GENESIS=https://kava-genesis-files.s3.us-east-1.amazonaws.com/kava_2222-10/genesis.json
      - PEERS=8b5c4a890c8ae7efbbe3360af71be1c3c3a9e12e@121.78.241.68:46656,ebc272824924ea1a27ea3183dd0b9ba713494f83@kava-mainnet-peer.autostake.com:26656,7ab4b78fbe5ee9e3777b21464a3162bd4cc17f57@peer-kava-01.stakeflow.io:1206
    params:
      storage:
        data:
          mount: /root/
    command:
      - bash
      - '-c'
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s https://raw.githubusercontent.com/kvas001/Nodes/main/General/main_cosmossdk.sh | bash '
    expose:
      - port: 22
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 8Gi
        storage:
          - size: 30Gi
          - name: data
            size: 310Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 100000
deployment:
  app:
    akash:
      profile: app
      count: 1
